apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controller
    ssh:
      address: 192.168.1.201
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  - role: controller
    ssh:
      address: 192.168.1.202
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  - role: controller
    ssh:
      address: 192.168.1.203
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  - role: worker
    ssh:
      address: 192.168.1.204
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  - role: worker
    ssh:
      address: 192.168.1.205
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  - role: worker
    ssh:
      address: 192.168.1.206
      user: root
      port: 22
      keyPath: C:\Users\saule\Documents\id_rsa
  k0s:
    version: v1.28.7+k0s.0
    versionChannel: stable
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: covi-k0s-cluster
      spec:
        network:
          provider: calico
        telemetry:
          enabled: false
        storage:
          type: etcd